version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml"
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "*.desktop"
]
SPDX-FileCopyrightText = "Google"
SPDX-License-Identifier = "LicenseRef-unknown"
